# SPDX-FileCopyrightText: 2022-2025 Helmholtz-Zentrum hereon GmbH
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileContributor: Carsten Lemmen <carsten.lemmen@hereon.de
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.3
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
      - id: check-gitlab-ci
  #     - id: check-readthedocs
  # For the following, an up-to-date zenode deposit schema is
  # need which is currently broken upstream
  # - repo: https://github.com/python-jsonschema/check-jsonschema
  #   rev: 0.27.3
  #   hooks:
  #     - id: check-jsonschema
  #       name: "Check Zenodo Metadata"
  #       files: ^\.zenodo.json$
  #       types: [json]
  #       args:
  #         [
  #           "--schemafile",
  #           "https://github.com/zenodraft/metadata-schema-zenodo/blob/main/schema.json",
  #         ]
  # - repo: https://github.com/lorenzwalthert/precommit
  # rev: v0.4.3
  # hooks:
  #   - id: lintr
  #     types: [r]
